# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 696876cb82aa1a82b2825bfcc3095f1e19ddf2e868dc404743dd5eaadbffd19a70d55794b4e90a6ebff7e20c8b3a9ca8a4744b4955f3f132823913dfdc4110c6

test:
  secret_key_base: 3cfce9e16e62dabbb0b556280ef57a46852e6c0e35c3d4ceaf14885ef9c7a480cae09a39eb17229238879a2b9db64d4239c45f942e0a6c26539965f585f8d5e2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
